---
actions:
  to: kubernetes/jvm/image.yaml
---
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Image","apiVersion":"kpack.io/v1alpha1","metadata":{"name":"hello-function-tbs-jvm","namespace":"default","creationTimestamp":null},"spec":{"tag":"gcr.io/pa-ddobrin/hello-function:jvm","builder":{"kind":"ClusterBuilder","name":"base"},"serviceAccount":"default","source":{"git":{"url":"https://github.com/ddobrin/spring-native-function-knative.git","revision":"main"}},"build":{"env":[{"name":"BP_JVM_VERSION","value":"11"},{"name":"BP_MAVEN_BUILD_ARGUMENTS","value":"-Dmaven.test.skip=true package spring-boot:repackage"}],"resources":{}}},"status":{}}'
  creationTimestamp: null
  name: {{artifactId}}-kpack-jvm
  namespace: default
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "11"
    - name: BP_MAVEN_BUILD_ARGUMENTS
      value: -Dmaven.test.skip=true package spring-boot:repackage
    resources: {}
  builder:
    kind: ClusterBuilder
    name: base
  serviceAccount: default
  source:
    git:
      revision: main
      url: https://github.com/ddobrin/spring-native-function-knative.git
  tag: {{artifactId}}-jvm:{{artifactVersion}}
status: {}
