---
actions:
  to: kubernetes/jvm/service.yaml
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{artifactId}}
  namespace: {{artifactId}}
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: {{artifactId}}-jvm:{{artifactVersion}}
      name: hello-function-v1
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: TARGET
          value: From Serverless Test - Spring Function on JVM
        image: {{artifactId}}-jvm:{{artifactVersion}} 
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
