apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: accessing-data-mysql
  name: accessing-data-mysql-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: accessing-data-mysql
  sessionAffinity: None
  type: LoadBalancer