apiVersion: accelerator.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: spring-sql-jpa
spec:
  git:
    url: https://github.com/simple-starters/accelerator-spring-sql-jpa
    ref:
      branch: mega
