---
actions:
  to: kubernetes/app/deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{artifactId}}
  name: {{artifactId}}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{artifactId}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{artifactId}}
    spec:
      containers:
      - image: {{artifactId}}:{{artifactVersion}}
        imagePullPolicy: IfNotPresent
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8sdev
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /actuator/info
            port: 8080
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          periodSeconds: 3
          failureThreshold: 20
          httpGet:
            path: /actuator/health
            port: 8080




