---
conditional:
  onDependency: mysql-connector-java
actions:
  inject:
    after: "env:"
    to: kubernetes/app/deployment.yaml
    skip: MYSQL_DATABASE
---
          - name: MYSQL_DATABASE
            value: my_database
          - name: MYSQL_USER
            value: springuser
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-password